// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: tap/ads/v1/advertisers.proto

package adsv1

import (
	v1 "github.com/real-evolution/tapproto/lib/go/tap/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for the ListAdvertisers method.
type ListAdvertisersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Filter by advertiser state.
	IsActive *bool `protobuf:"varint,1,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	// Pagination parameters.
	Page *v1.Page `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ListAdvertisersRequest) Reset() {
	*x = ListAdvertisersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdvertisersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertisersRequest) ProtoMessage() {}

func (x *ListAdvertisersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertisersRequest.ProtoReflect.Descriptor instead.
func (*ListAdvertisersRequest) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{0}
}

func (x *ListAdvertisersRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListAdvertisersRequest) GetPage() *v1.Page {
	if x != nil {
		return x.Page
	}
	return nil
}

// The response message for the ListAdvertisers method.
type ListAdvertisersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The advertisers.
	Items []*Advertiser `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// The next page cursor.
	NextCursor []byte `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3,oneof" json:"next_cursor,omitempty"`
}

func (x *ListAdvertisersResponse) Reset() {
	*x = ListAdvertisersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAdvertisersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdvertisersResponse) ProtoMessage() {}

func (x *ListAdvertisersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdvertisersResponse.ProtoReflect.Descriptor instead.
func (*ListAdvertisersResponse) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{1}
}

func (x *ListAdvertisersResponse) GetItems() []*Advertiser {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListAdvertisersResponse) GetNextCursor() []byte {
	if x != nil {
		return x.NextCursor
	}
	return nil
}

// The request message for the GetAdvertiser method.
type GetAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser to retrieve.
	Id *AdvertiserID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAdvertiserRequest) Reset() {
	*x = GetAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertiserRequest) ProtoMessage() {}

func (x *GetAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*GetAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdvertiserRequest) GetId() *AdvertiserID {
	if x != nil {
		return x.Id
	}
	return nil
}

// The response message for the GetAdvertiser method.
type GetAdvertiserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The advertiser.
	Advertiser *Advertiser `protobuf:"bytes,1,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
}

func (x *GetAdvertiserResponse) Reset() {
	*x = GetAdvertiserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdvertiserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdvertiserResponse) ProtoMessage() {}

func (x *GetAdvertiserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdvertiserResponse.ProtoReflect.Descriptor instead.
func (*GetAdvertiserResponse) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{3}
}

func (x *GetAdvertiserResponse) GetAdvertiser() *Advertiser {
	if x != nil {
		return x.Advertiser
	}
	return nil
}

// The request message for the CreateAdvertiser method.
type CreateAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser to create.
	Id *AdvertiserID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name of the advertiser.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The state of the advertiser.
	IsActive bool `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (x *CreateAdvertiserRequest) Reset() {
	*x = CreateAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertiserRequest) ProtoMessage() {}

func (x *CreateAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*CreateAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAdvertiserRequest) GetId() *AdvertiserID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAdvertiserRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateAdvertiserRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// The response message for the CreateAdvertiser method.
type CreateAdvertiserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The advertiser.
	Advertiser *Advertiser `protobuf:"bytes,1,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
}

func (x *CreateAdvertiserResponse) Reset() {
	*x = CreateAdvertiserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertiserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertiserResponse) ProtoMessage() {}

func (x *CreateAdvertiserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertiserResponse.ProtoReflect.Descriptor instead.
func (*CreateAdvertiserResponse) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAdvertiserResponse) GetAdvertiser() *Advertiser {
	if x != nil {
		return x.Advertiser
	}
	return nil
}

// The request message for the UpdateAdvertiser method.
type UpdateAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser to update.
	Id *AdvertiserID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name of the advertiser.
	DisplayName *string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3,oneof" json:"display_name,omitempty"`
	// The state of the advertiser.
	IsActive *bool `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
}

func (x *UpdateAdvertiserRequest) Reset() {
	*x = UpdateAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertiserRequest) ProtoMessage() {}

func (x *UpdateAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*UpdateAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAdvertiserRequest) GetId() *AdvertiserID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateAdvertiserRequest) GetDisplayName() string {
	if x != nil && x.DisplayName != nil {
		return *x.DisplayName
	}
	return ""
}

func (x *UpdateAdvertiserRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// The response message for the UpdateAdvertiser method.
type UpdateAdvertiserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The updated advertiser.
	Advertiser *Advertiser `protobuf:"bytes,1,opt,name=advertiser,proto3" json:"advertiser,omitempty"`
}

func (x *UpdateAdvertiserResponse) Reset() {
	*x = UpdateAdvertiserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAdvertiserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAdvertiserResponse) ProtoMessage() {}

func (x *UpdateAdvertiserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAdvertiserResponse.ProtoReflect.Descriptor instead.
func (*UpdateAdvertiserResponse) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAdvertiserResponse) GetAdvertiser() *Advertiser {
	if x != nil {
		return x.Advertiser
	}
	return nil
}

// The request message for the DeleteAdvertiser method.
type DeleteAdvertiserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser to delete.
	Id *AdvertiserID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAdvertiserRequest) Reset() {
	*x = DeleteAdvertiserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdvertiserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertiserRequest) ProtoMessage() {}

func (x *DeleteAdvertiserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertiserRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdvertiserRequest) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAdvertiserRequest) GetId() *AdvertiserID {
	if x != nil {
		return x.Id
	}
	return nil
}

// The response message for the DeleteAdvertiser method.
type DeleteAdvertiserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAdvertiserResponse) Reset() {
	*x = DeleteAdvertiserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAdvertiserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdvertiserResponse) ProtoMessage() {}

func (x *DeleteAdvertiserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdvertiserResponse.ProtoReflect.Descriptor instead.
func (*DeleteAdvertiserResponse) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{9}
}

// A message to represent a advertiser ID.
type AdvertiserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser.
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *AdvertiserID) Reset() {
	*x = AdvertiserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdvertiserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvertiserID) ProtoMessage() {}

func (x *AdvertiserID) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvertiserID.ProtoReflect.Descriptor instead.
func (*AdvertiserID) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{10}
}

func (x *AdvertiserID) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// A message to represent a advertiser
type Advertiser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the advertiser.
	Id *AdvertiserID `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The display name of the advertiser.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The state of the advertiser.
	IsActive bool `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// The creation time of the advertiser.
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// The last update time of the advertiser.
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
}

func (x *Advertiser) Reset() {
	*x = Advertiser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tap_ads_v1_advertisers_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Advertiser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advertiser) ProtoMessage() {}

func (x *Advertiser) ProtoReflect() protoreflect.Message {
	mi := &file_tap_ads_v1_advertisers_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advertiser.ProtoReflect.Descriptor instead.
func (*Advertiser) Descriptor() ([]byte, []int) {
	return file_tap_ads_v1_advertisers_proto_rawDescGZIP(), []int{11}
}

func (x *Advertiser) GetId() *AdvertiserID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Advertiser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Advertiser) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Advertiser) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Advertiser) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

var File_tap_ads_v1_advertisers_proto protoreflect.FileDescriptor

var file_tap_ads_v1_advertisers_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x74, 0x61, 0x70, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x74, 0x61, 0x70,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x70, 0x0a, 0x16, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x12, 0x26, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x42, 0x0c,
	0x0a, 0x0a, 0x5f, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x7d, 0x0a, 0x17,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x24, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75,
	0x72, 0x73, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0a, 0x6e, 0x65,
	0x78, 0x74, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x63, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x22, 0x40, 0x0a, 0x14, 0x47,
	0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x18, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4f, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x61, 0x70,
	0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x52, 0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x22, 0x83,
	0x01, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70,
	0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x22, 0x52, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x0a, 0x61, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x22, 0xac, 0x01, 0x0a, 0x17, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64,
	0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x26,
	0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x12, 0x20, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x48, 0x01, 0x52, 0x08, 0x69, 0x73, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x69, 0x73,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x22, 0x52, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52,
	0x0a, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x22, 0x43, 0x0a, 0x17, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x1a, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x24, 0x0a, 0x0c,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xf0, 0x01, 0x0a, 0x0a, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x12, 0x28, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x64,
	0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x69, 0x73, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x69, 0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x3b, 0x0a, 0x0b, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x32, 0xe3, 0x03, 0x0a, 0x12, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a, 0x0a, 0x0f,
	0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x12,
	0x22, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x74, 0x61, 0x70, 0x2e,
	0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x61,
	0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d,
	0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x72, 0x12, 0x23, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a,
	0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x72, 0x12, 0x23, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5d, 0x0a, 0x10,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72,
	0x12, 0x23, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0xa8, 0x01, 0x0a, 0x0e,
	0x63, 0x6f, 0x6d, 0x2e, 0x74, 0x61, 0x70, 0x2e, 0x61, 0x64, 0x73, 0x2e, 0x76, 0x31, 0x42, 0x10,
	0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x72, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x65, 0x61, 0x6c, 0x2d, 0x65, 0x76, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x61,
	0x70, 0x2f, 0x61, 0x64, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x64, 0x73, 0x76, 0x31, 0xa2, 0x02,
	0x03, 0x54, 0x41, 0x58, 0xaa, 0x02, 0x0a, 0x54, 0x61, 0x70, 0x2e, 0x41, 0x64, 0x73, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x0a, 0x54, 0x61, 0x70, 0x5c, 0x41, 0x64, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02,
	0x16, 0x54, 0x61, 0x70, 0x5c, 0x41, 0x64, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x0c, 0x54, 0x61, 0x70, 0x3a, 0x3a, 0x41,
	0x64, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tap_ads_v1_advertisers_proto_rawDescOnce sync.Once
	file_tap_ads_v1_advertisers_proto_rawDescData = file_tap_ads_v1_advertisers_proto_rawDesc
)

func file_tap_ads_v1_advertisers_proto_rawDescGZIP() []byte {
	file_tap_ads_v1_advertisers_proto_rawDescOnce.Do(func() {
		file_tap_ads_v1_advertisers_proto_rawDescData = protoimpl.X.CompressGZIP(file_tap_ads_v1_advertisers_proto_rawDescData)
	})
	return file_tap_ads_v1_advertisers_proto_rawDescData
}

var file_tap_ads_v1_advertisers_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_tap_ads_v1_advertisers_proto_goTypes = []interface{}{
	(*ListAdvertisersRequest)(nil),   // 0: tap.ads.v1.ListAdvertisersRequest
	(*ListAdvertisersResponse)(nil),  // 1: tap.ads.v1.ListAdvertisersResponse
	(*GetAdvertiserRequest)(nil),     // 2: tap.ads.v1.GetAdvertiserRequest
	(*GetAdvertiserResponse)(nil),    // 3: tap.ads.v1.GetAdvertiserResponse
	(*CreateAdvertiserRequest)(nil),  // 4: tap.ads.v1.CreateAdvertiserRequest
	(*CreateAdvertiserResponse)(nil), // 5: tap.ads.v1.CreateAdvertiserResponse
	(*UpdateAdvertiserRequest)(nil),  // 6: tap.ads.v1.UpdateAdvertiserRequest
	(*UpdateAdvertiserResponse)(nil), // 7: tap.ads.v1.UpdateAdvertiserResponse
	(*DeleteAdvertiserRequest)(nil),  // 8: tap.ads.v1.DeleteAdvertiserRequest
	(*DeleteAdvertiserResponse)(nil), // 9: tap.ads.v1.DeleteAdvertiserResponse
	(*AdvertiserID)(nil),             // 10: tap.ads.v1.AdvertiserID
	(*Advertiser)(nil),               // 11: tap.ads.v1.Advertiser
	(*v1.Page)(nil),                  // 12: tap.types.v1.Page
	(*timestamppb.Timestamp)(nil),    // 13: google.protobuf.Timestamp
}
var file_tap_ads_v1_advertisers_proto_depIdxs = []int32{
	12, // 0: tap.ads.v1.ListAdvertisersRequest.page:type_name -> tap.types.v1.Page
	11, // 1: tap.ads.v1.ListAdvertisersResponse.items:type_name -> tap.ads.v1.Advertiser
	10, // 2: tap.ads.v1.GetAdvertiserRequest.id:type_name -> tap.ads.v1.AdvertiserID
	11, // 3: tap.ads.v1.GetAdvertiserResponse.advertiser:type_name -> tap.ads.v1.Advertiser
	10, // 4: tap.ads.v1.CreateAdvertiserRequest.id:type_name -> tap.ads.v1.AdvertiserID
	11, // 5: tap.ads.v1.CreateAdvertiserResponse.advertiser:type_name -> tap.ads.v1.Advertiser
	10, // 6: tap.ads.v1.UpdateAdvertiserRequest.id:type_name -> tap.ads.v1.AdvertiserID
	11, // 7: tap.ads.v1.UpdateAdvertiserResponse.advertiser:type_name -> tap.ads.v1.Advertiser
	10, // 8: tap.ads.v1.DeleteAdvertiserRequest.id:type_name -> tap.ads.v1.AdvertiserID
	10, // 9: tap.ads.v1.Advertiser.id:type_name -> tap.ads.v1.AdvertiserID
	13, // 10: tap.ads.v1.Advertiser.create_time:type_name -> google.protobuf.Timestamp
	13, // 11: tap.ads.v1.Advertiser.update_time:type_name -> google.protobuf.Timestamp
	0,  // 12: tap.ads.v1.AdvertisersService.ListAdvertisers:input_type -> tap.ads.v1.ListAdvertisersRequest
	2,  // 13: tap.ads.v1.AdvertisersService.GetAdvertiser:input_type -> tap.ads.v1.GetAdvertiserRequest
	4,  // 14: tap.ads.v1.AdvertisersService.CreateAdvertiser:input_type -> tap.ads.v1.CreateAdvertiserRequest
	6,  // 15: tap.ads.v1.AdvertisersService.UpdateAdvertiser:input_type -> tap.ads.v1.UpdateAdvertiserRequest
	8,  // 16: tap.ads.v1.AdvertisersService.DeleteAdvertiser:input_type -> tap.ads.v1.DeleteAdvertiserRequest
	1,  // 17: tap.ads.v1.AdvertisersService.ListAdvertisers:output_type -> tap.ads.v1.ListAdvertisersResponse
	3,  // 18: tap.ads.v1.AdvertisersService.GetAdvertiser:output_type -> tap.ads.v1.GetAdvertiserResponse
	5,  // 19: tap.ads.v1.AdvertisersService.CreateAdvertiser:output_type -> tap.ads.v1.CreateAdvertiserResponse
	7,  // 20: tap.ads.v1.AdvertisersService.UpdateAdvertiser:output_type -> tap.ads.v1.UpdateAdvertiserResponse
	9,  // 21: tap.ads.v1.AdvertisersService.DeleteAdvertiser:output_type -> tap.ads.v1.DeleteAdvertiserResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tap_ads_v1_advertisers_proto_init() }
func file_tap_ads_v1_advertisers_proto_init() {
	if File_tap_ads_v1_advertisers_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tap_ads_v1_advertisers_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdvertisersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAdvertisersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdvertiserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdvertiserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAdvertiserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAdvertiserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAdvertiserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdvertiserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tap_ads_v1_advertisers_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Advertiser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_tap_ads_v1_advertisers_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_tap_ads_v1_advertisers_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_tap_ads_v1_advertisers_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tap_ads_v1_advertisers_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tap_ads_v1_advertisers_proto_goTypes,
		DependencyIndexes: file_tap_ads_v1_advertisers_proto_depIdxs,
		MessageInfos:      file_tap_ads_v1_advertisers_proto_msgTypes,
	}.Build()
	File_tap_ads_v1_advertisers_proto = out.File
	file_tap_ads_v1_advertisers_proto_rawDesc = nil
	file_tap_ads_v1_advertisers_proto_goTypes = nil
	file_tap_ads_v1_advertisers_proto_depIdxs = nil
}
