// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: tap/ads/v1/passes.proto

package adsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PassesService_ListPasses_FullMethodName            = "/tap.ads.v1.PassesService/ListPasses"
	PassesService_GetPass_FullMethodName               = "/tap.ads.v1.PassesService/GetPass"
	PassesService_CreatePass_FullMethodName            = "/tap.ads.v1.PassesService/CreatePass"
	PassesService_UpdatePass_FullMethodName            = "/tap.ads.v1.PassesService/UpdatePass"
	PassesService_DeletePass_FullMethodName            = "/tap.ads.v1.PassesService/DeletePass"
	PassesService_ListPassRequirements_FullMethodName  = "/tap.ads.v1.PassesService/ListPassRequirements"
	PassesService_CreatePassRequirement_FullMethodName = "/tap.ads.v1.PassesService/CreatePassRequirement"
	PassesService_DeletePassRequirement_FullMethodName = "/tap.ads.v1.PassesService/DeletePassRequirement"
	PassesService_CanSubscribeToPass_FullMethodName    = "/tap.ads.v1.PassesService/CanSubscribeToPass"
)

// PassesServiceClient is the client API for PassesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PassesServiceClient interface {
	ListPasses(ctx context.Context, in *ListPassesRequest, opts ...grpc.CallOption) (*ListPassesResponse, error)
	GetPass(ctx context.Context, in *GetPassRequest, opts ...grpc.CallOption) (*GetPassResponse, error)
	CreatePass(ctx context.Context, in *CreatePassRequest, opts ...grpc.CallOption) (*CreatePassResponse, error)
	UpdatePass(ctx context.Context, in *UpdatePassRequest, opts ...grpc.CallOption) (*UpdatePassResponse, error)
	DeletePass(ctx context.Context, in *DeletePassRequest, opts ...grpc.CallOption) (*DeletePassResponse, error)
	ListPassRequirements(ctx context.Context, in *ListPassRequirementsRequest, opts ...grpc.CallOption) (*ListPassRequirementsResponse, error)
	CreatePassRequirement(ctx context.Context, in *CreatePassRequirementRequest, opts ...grpc.CallOption) (*CreatePassRequirementResponse, error)
	DeletePassRequirement(ctx context.Context, in *DeletePassRequirementRequest, opts ...grpc.CallOption) (*DeletePassRequirementResponse, error)
	CanSubscribeToPass(ctx context.Context, in *CanSubscribeToPassRequest, opts ...grpc.CallOption) (*CanSubscribeToPassResponse, error)
}

type passesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPassesServiceClient(cc grpc.ClientConnInterface) PassesServiceClient {
	return &passesServiceClient{cc}
}

func (c *passesServiceClient) ListPasses(ctx context.Context, in *ListPassesRequest, opts ...grpc.CallOption) (*ListPassesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPassesResponse)
	err := c.cc.Invoke(ctx, PassesService_ListPasses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) GetPass(ctx context.Context, in *GetPassRequest, opts ...grpc.CallOption) (*GetPassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPassResponse)
	err := c.cc.Invoke(ctx, PassesService_GetPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) CreatePass(ctx context.Context, in *CreatePassRequest, opts ...grpc.CallOption) (*CreatePassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePassResponse)
	err := c.cc.Invoke(ctx, PassesService_CreatePass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) UpdatePass(ctx context.Context, in *UpdatePassRequest, opts ...grpc.CallOption) (*UpdatePassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePassResponse)
	err := c.cc.Invoke(ctx, PassesService_UpdatePass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) DeletePass(ctx context.Context, in *DeletePassRequest, opts ...grpc.CallOption) (*DeletePassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePassResponse)
	err := c.cc.Invoke(ctx, PassesService_DeletePass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) ListPassRequirements(ctx context.Context, in *ListPassRequirementsRequest, opts ...grpc.CallOption) (*ListPassRequirementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPassRequirementsResponse)
	err := c.cc.Invoke(ctx, PassesService_ListPassRequirements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) CreatePassRequirement(ctx context.Context, in *CreatePassRequirementRequest, opts ...grpc.CallOption) (*CreatePassRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePassRequirementResponse)
	err := c.cc.Invoke(ctx, PassesService_CreatePassRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) DeletePassRequirement(ctx context.Context, in *DeletePassRequirementRequest, opts ...grpc.CallOption) (*DeletePassRequirementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePassRequirementResponse)
	err := c.cc.Invoke(ctx, PassesService_DeletePassRequirement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passesServiceClient) CanSubscribeToPass(ctx context.Context, in *CanSubscribeToPassRequest, opts ...grpc.CallOption) (*CanSubscribeToPassResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CanSubscribeToPassResponse)
	err := c.cc.Invoke(ctx, PassesService_CanSubscribeToPass_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PassesServiceServer is the server API for PassesService service.
// All implementations must embed UnimplementedPassesServiceServer
// for forward compatibility
type PassesServiceServer interface {
	ListPasses(context.Context, *ListPassesRequest) (*ListPassesResponse, error)
	GetPass(context.Context, *GetPassRequest) (*GetPassResponse, error)
	CreatePass(context.Context, *CreatePassRequest) (*CreatePassResponse, error)
	UpdatePass(context.Context, *UpdatePassRequest) (*UpdatePassResponse, error)
	DeletePass(context.Context, *DeletePassRequest) (*DeletePassResponse, error)
	ListPassRequirements(context.Context, *ListPassRequirementsRequest) (*ListPassRequirementsResponse, error)
	CreatePassRequirement(context.Context, *CreatePassRequirementRequest) (*CreatePassRequirementResponse, error)
	DeletePassRequirement(context.Context, *DeletePassRequirementRequest) (*DeletePassRequirementResponse, error)
	CanSubscribeToPass(context.Context, *CanSubscribeToPassRequest) (*CanSubscribeToPassResponse, error)
	mustEmbedUnimplementedPassesServiceServer()
}

// UnimplementedPassesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPassesServiceServer struct {
}

func (UnimplementedPassesServiceServer) ListPasses(context.Context, *ListPassesRequest) (*ListPassesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPasses not implemented")
}
func (UnimplementedPassesServiceServer) GetPass(context.Context, *GetPassRequest) (*GetPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPass not implemented")
}
func (UnimplementedPassesServiceServer) CreatePass(context.Context, *CreatePassRequest) (*CreatePassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePass not implemented")
}
func (UnimplementedPassesServiceServer) UpdatePass(context.Context, *UpdatePassRequest) (*UpdatePassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePass not implemented")
}
func (UnimplementedPassesServiceServer) DeletePass(context.Context, *DeletePassRequest) (*DeletePassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePass not implemented")
}
func (UnimplementedPassesServiceServer) ListPassRequirements(context.Context, *ListPassRequirementsRequest) (*ListPassRequirementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPassRequirements not implemented")
}
func (UnimplementedPassesServiceServer) CreatePassRequirement(context.Context, *CreatePassRequirementRequest) (*CreatePassRequirementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePassRequirement not implemented")
}
func (UnimplementedPassesServiceServer) DeletePassRequirement(context.Context, *DeletePassRequirementRequest) (*DeletePassRequirementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassRequirement not implemented")
}
func (UnimplementedPassesServiceServer) CanSubscribeToPass(context.Context, *CanSubscribeToPassRequest) (*CanSubscribeToPassResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CanSubscribeToPass not implemented")
}
func (UnimplementedPassesServiceServer) mustEmbedUnimplementedPassesServiceServer() {}

// UnsafePassesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PassesServiceServer will
// result in compilation errors.
type UnsafePassesServiceServer interface {
	mustEmbedUnimplementedPassesServiceServer()
}

func RegisterPassesServiceServer(s grpc.ServiceRegistrar, srv PassesServiceServer) {
	s.RegisterService(&PassesService_ServiceDesc, srv)
}

func _PassesService_ListPasses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPassesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).ListPasses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_ListPasses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).ListPasses(ctx, req.(*ListPassesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_GetPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).GetPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_GetPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).GetPass(ctx, req.(*GetPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_CreatePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).CreatePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_CreatePass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).CreatePass(ctx, req.(*CreatePassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_UpdatePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).UpdatePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_UpdatePass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).UpdatePass(ctx, req.(*UpdatePassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_DeletePass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).DeletePass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_DeletePass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).DeletePass(ctx, req.(*DeletePassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_ListPassRequirements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPassRequirementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).ListPassRequirements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_ListPassRequirements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).ListPassRequirements(ctx, req.(*ListPassRequirementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_CreatePassRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePassRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).CreatePassRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_CreatePassRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).CreatePassRequirement(ctx, req.(*CreatePassRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_DeletePassRequirement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePassRequirementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).DeletePassRequirement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_DeletePassRequirement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).DeletePassRequirement(ctx, req.(*DeletePassRequirementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PassesService_CanSubscribeToPass_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CanSubscribeToPassRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PassesServiceServer).CanSubscribeToPass(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PassesService_CanSubscribeToPass_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PassesServiceServer).CanSubscribeToPass(ctx, req.(*CanSubscribeToPassRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PassesService_ServiceDesc is the grpc.ServiceDesc for PassesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PassesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tap.ads.v1.PassesService",
	HandlerType: (*PassesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPasses",
			Handler:    _PassesService_ListPasses_Handler,
		},
		{
			MethodName: "GetPass",
			Handler:    _PassesService_GetPass_Handler,
		},
		{
			MethodName: "CreatePass",
			Handler:    _PassesService_CreatePass_Handler,
		},
		{
			MethodName: "UpdatePass",
			Handler:    _PassesService_UpdatePass_Handler,
		},
		{
			MethodName: "DeletePass",
			Handler:    _PassesService_DeletePass_Handler,
		},
		{
			MethodName: "ListPassRequirements",
			Handler:    _PassesService_ListPassRequirements_Handler,
		},
		{
			MethodName: "CreatePassRequirement",
			Handler:    _PassesService_CreatePassRequirement_Handler,
		},
		{
			MethodName: "DeletePassRequirement",
			Handler:    _PassesService_DeletePassRequirement_Handler,
		},
		{
			MethodName: "CanSubscribeToPass",
			Handler:    _PassesService_CanSubscribeToPass_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tap/ads/v1/passes.proto",
}
