// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: tap/sub/v1/events.proto

package subv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EventsService_GetEventBatch_FullMethodName = "/tap.sub.v1.EventsService/GetEventBatch"
	EventsService_CommitEvent_FullMethodName   = "/tap.sub.v1.EventsService/CommitEvent"
	EventsService_RevertEvent_FullMethodName   = "/tap.sub.v1.EventsService/RevertEvent"
)

// EventsServiceClient is the client API for EventsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The events service.
type EventsServiceClient interface {
	// Gets a batch of events.
	GetEventBatch(ctx context.Context, in *GetEventBatchRequest, opts ...grpc.CallOption) (*GetEventBatchResponse, error)
	// Commits an event.
	CommitEvent(ctx context.Context, in *CommitEventRequest, opts ...grpc.CallOption) (*CommitEventResponse, error)
	// Reverts an event.
	RevertEvent(ctx context.Context, in *RevertEventRequest, opts ...grpc.CallOption) (*RevertEventResponse, error)
}

type eventsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventsServiceClient(cc grpc.ClientConnInterface) EventsServiceClient {
	return &eventsServiceClient{cc}
}

func (c *eventsServiceClient) GetEventBatch(ctx context.Context, in *GetEventBatchRequest, opts ...grpc.CallOption) (*GetEventBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventBatchResponse)
	err := c.cc.Invoke(ctx, EventsService_GetEventBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) CommitEvent(ctx context.Context, in *CommitEventRequest, opts ...grpc.CallOption) (*CommitEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitEventResponse)
	err := c.cc.Invoke(ctx, EventsService_CommitEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eventsServiceClient) RevertEvent(ctx context.Context, in *RevertEventRequest, opts ...grpc.CallOption) (*RevertEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevertEventResponse)
	err := c.cc.Invoke(ctx, EventsService_RevertEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventsServiceServer is the server API for EventsService service.
// All implementations must embed UnimplementedEventsServiceServer
// for forward compatibility
//
// The events service.
type EventsServiceServer interface {
	// Gets a batch of events.
	GetEventBatch(context.Context, *GetEventBatchRequest) (*GetEventBatchResponse, error)
	// Commits an event.
	CommitEvent(context.Context, *CommitEventRequest) (*CommitEventResponse, error)
	// Reverts an event.
	RevertEvent(context.Context, *RevertEventRequest) (*RevertEventResponse, error)
	mustEmbedUnimplementedEventsServiceServer()
}

// UnimplementedEventsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventsServiceServer struct {
}

func (UnimplementedEventsServiceServer) GetEventBatch(context.Context, *GetEventBatchRequest) (*GetEventBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEventBatch not implemented")
}
func (UnimplementedEventsServiceServer) CommitEvent(context.Context, *CommitEventRequest) (*CommitEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitEvent not implemented")
}
func (UnimplementedEventsServiceServer) RevertEvent(context.Context, *RevertEventRequest) (*RevertEventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevertEvent not implemented")
}
func (UnimplementedEventsServiceServer) mustEmbedUnimplementedEventsServiceServer() {}

// UnsafeEventsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventsServiceServer will
// result in compilation errors.
type UnsafeEventsServiceServer interface {
	mustEmbedUnimplementedEventsServiceServer()
}

func RegisterEventsServiceServer(s grpc.ServiceRegistrar, srv EventsServiceServer) {
	s.RegisterService(&EventsService_ServiceDesc, srv)
}

func _EventsService_GetEventBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).GetEventBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_GetEventBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).GetEventBatch(ctx, req.(*GetEventBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_CommitEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).CommitEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_CommitEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).CommitEvent(ctx, req.(*CommitEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EventsService_RevertEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevertEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventsServiceServer).RevertEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EventsService_RevertEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventsServiceServer).RevertEvent(ctx, req.(*RevertEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventsService_ServiceDesc is the grpc.ServiceDesc for EventsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tap.sub.v1.EventsService",
	HandlerType: (*EventsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEventBatch",
			Handler:    _EventsService_GetEventBatch_Handler,
		},
		{
			MethodName: "CommitEvent",
			Handler:    _EventsService_CommitEvent_Handler,
		},
		{
			MethodName: "RevertEvent",
			Handler:    _EventsService_RevertEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tap/sub/v1/events.proto",
}
