// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: tap/campaign/v1/campaigns.proto

package campaignv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CampaignsService_ListCampaigns_FullMethodName     = "/tap.campaign.v1.CampaignsService/ListCampaigns"
	CampaignsService_GetCampaign_FullMethodName       = "/tap.campaign.v1.CampaignsService/GetCampaign"
	CampaignsService_CreateCampaign_FullMethodName    = "/tap.campaign.v1.CampaignsService/CreateCampaign"
	CampaignsService_SetCampaignState_FullMethodName  = "/tap.campaign.v1.CampaignsService/SetCampaignState"
	CampaignsService_PickAd_FullMethodName            = "/tap.campaign.v1.CampaignsService/PickAd"
	CampaignsService_ListCampaignViews_FullMethodName = "/tap.campaign.v1.CampaignsService/ListCampaignViews"
	CampaignsService_RegisterAdView_FullMethodName    = "/tap.campaign.v1.CampaignsService/RegisterAdView"
)

// CampaignsServiceClient is the client API for CampaignsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignsServiceClient interface {
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error)
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error)
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error)
	SetCampaignState(ctx context.Context, in *SetCampaignStateRequest, opts ...grpc.CallOption) (*SetCampaignStateResponse, error)
	PickAd(ctx context.Context, in *PickAdRequest, opts ...grpc.CallOption) (*PickAdResponse, error)
	ListCampaignViews(ctx context.Context, in *ListCampaignViewsRequest, opts ...grpc.CallOption) (*ListCampaignViewsResponse, error)
	RegisterAdView(ctx context.Context, in *RegisterAdViewRequest, opts ...grpc.CallOption) (*RegisterAdViewResponse, error)
}

type campaignsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignsServiceClient(cc grpc.ClientConnInterface) CampaignsServiceClient {
	return &campaignsServiceClient{cc}
}

func (c *campaignsServiceClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsResponse)
	err := c.cc.Invoke(ctx, CampaignsService_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsService_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignsService_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) SetCampaignState(ctx context.Context, in *SetCampaignStateRequest, opts ...grpc.CallOption) (*SetCampaignStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetCampaignStateResponse)
	err := c.cc.Invoke(ctx, CampaignsService_SetCampaignState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) PickAd(ctx context.Context, in *PickAdRequest, opts ...grpc.CallOption) (*PickAdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickAdResponse)
	err := c.cc.Invoke(ctx, CampaignsService_PickAd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) ListCampaignViews(ctx context.Context, in *ListCampaignViewsRequest, opts ...grpc.CallOption) (*ListCampaignViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignViewsResponse)
	err := c.cc.Invoke(ctx, CampaignsService_ListCampaignViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignsServiceClient) RegisterAdView(ctx context.Context, in *RegisterAdViewRequest, opts ...grpc.CallOption) (*RegisterAdViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAdViewResponse)
	err := c.cc.Invoke(ctx, CampaignsService_RegisterAdView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignsServiceServer is the server API for CampaignsService service.
// All implementations must embed UnimplementedCampaignsServiceServer
// for forward compatibility
type CampaignsServiceServer interface {
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error)
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error)
	SetCampaignState(context.Context, *SetCampaignStateRequest) (*SetCampaignStateResponse, error)
	PickAd(context.Context, *PickAdRequest) (*PickAdResponse, error)
	ListCampaignViews(context.Context, *ListCampaignViewsRequest) (*ListCampaignViewsResponse, error)
	RegisterAdView(context.Context, *RegisterAdViewRequest) (*RegisterAdViewResponse, error)
	mustEmbedUnimplementedCampaignsServiceServer()
}

// UnimplementedCampaignsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCampaignsServiceServer struct {
}

func (UnimplementedCampaignsServiceServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedCampaignsServiceServer) GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedCampaignsServiceServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedCampaignsServiceServer) SetCampaignState(context.Context, *SetCampaignStateRequest) (*SetCampaignStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetCampaignState not implemented")
}
func (UnimplementedCampaignsServiceServer) PickAd(context.Context, *PickAdRequest) (*PickAdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PickAd not implemented")
}
func (UnimplementedCampaignsServiceServer) ListCampaignViews(context.Context, *ListCampaignViewsRequest) (*ListCampaignViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaignViews not implemented")
}
func (UnimplementedCampaignsServiceServer) RegisterAdView(context.Context, *RegisterAdViewRequest) (*RegisterAdViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAdView not implemented")
}
func (UnimplementedCampaignsServiceServer) mustEmbedUnimplementedCampaignsServiceServer() {}

// UnsafeCampaignsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignsServiceServer will
// result in compilation errors.
type UnsafeCampaignsServiceServer interface {
	mustEmbedUnimplementedCampaignsServiceServer()
}

func RegisterCampaignsServiceServer(s grpc.ServiceRegistrar, srv CampaignsServiceServer) {
	s.RegisterService(&CampaignsService_ServiceDesc, srv)
}

func _CampaignsService_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_SetCampaignState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetCampaignStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).SetCampaignState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_SetCampaignState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).SetCampaignState(ctx, req.(*SetCampaignStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_PickAd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PickAdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).PickAd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_PickAd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).PickAd(ctx, req.(*PickAdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_ListCampaignViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).ListCampaignViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_ListCampaignViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).ListCampaignViews(ctx, req.(*ListCampaignViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignsService_RegisterAdView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAdViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignsServiceServer).RegisterAdView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignsService_RegisterAdView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignsServiceServer).RegisterAdView(ctx, req.(*RegisterAdViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignsService_ServiceDesc is the grpc.ServiceDesc for CampaignsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tap.campaign.v1.CampaignsService",
	HandlerType: (*CampaignsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCampaigns",
			Handler:    _CampaignsService_ListCampaigns_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _CampaignsService_GetCampaign_Handler,
		},
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignsService_CreateCampaign_Handler,
		},
		{
			MethodName: "SetCampaignState",
			Handler:    _CampaignsService_SetCampaignState_Handler,
		},
		{
			MethodName: "PickAd",
			Handler:    _CampaignsService_PickAd_Handler,
		},
		{
			MethodName: "ListCampaignViews",
			Handler:    _CampaignsService_ListCampaignViews_Handler,
		},
		{
			MethodName: "RegisterAdView",
			Handler:    _CampaignsService_RegisterAdView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tap/campaign/v1/campaigns.proto",
}
