// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: tap/verify/v1/tickets.proto

package verifyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TicketService_ListTickets_FullMethodName             = "/tap.verify.v1.TicketService/ListTickets"
	TicketService_GetTicket_FullMethodName               = "/tap.verify.v1.TicketService/GetTicket"
	TicketService_CreateTicket_FullMethodName            = "/tap.verify.v1.TicketService/CreateTicket"
	TicketService_UpdateTicket_FullMethodName            = "/tap.verify.v1.TicketService/UpdateTicket"
	TicketService_DeleteTicket_FullMethodName            = "/tap.verify.v1.TicketService/DeleteTicket"
	TicketService_AddTicketTags_FullMethodName           = "/tap.verify.v1.TicketService/AddTicketTags"
	TicketService_ListTicketTags_FullMethodName          = "/tap.verify.v1.TicketService/ListTicketTags"
	TicketService_DeleteTicketTags_FullMethodName        = "/tap.verify.v1.TicketService/DeleteTicketTags"
	TicketService_Verify_FullMethodName                  = "/tap.verify.v1.TicketService/Verify"
	TicketService_ListTicketVerifications_FullMethodName = "/tap.verify.v1.TicketService/ListTicketVerifications"
	TicketService_IsApproved_FullMethodName              = "/tap.verify.v1.TicketService/IsApproved"
)

// TicketServiceClient is the client API for TicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicketServiceClient interface {
	// Lists tickets
	ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error)
	// Gets a ticket
	GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*GetTicketResponse, error)
	// Create a ticket
	CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketResponse, error)
	// Updates a ticket
	UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*UpdateTicketResponse, error)
	// Deletes a ticket
	DeleteTicket(ctx context.Context, in *DeleteTicketRequest, opts ...grpc.CallOption) (*DeleteTicketResponse, error)
	// Add tags
	AddTicketTags(ctx context.Context, in *AddTicketTagsRequest, opts ...grpc.CallOption) (*AddTicketTagsResponse, error)
	// List tags
	ListTicketTags(ctx context.Context, in *ListTicketTagsRequest, opts ...grpc.CallOption) (*ListTicketTagsResponse, error)
	// Remove tags
	DeleteTicketTags(ctx context.Context, in *DeleteTicketTagsRequest, opts ...grpc.CallOption) (*DeleteTicketTagsResponse, error)
	// Verify a ticket
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
	// List ticket verifications
	ListTicketVerifications(ctx context.Context, in *ListTicketVerificationsRequest, opts ...grpc.CallOption) (*ListTicketVerificationsResponse, error)
	// check whether a ticket is approved
	IsApproved(ctx context.Context, in *IsApprovedRequest, opts ...grpc.CallOption) (*IsApprovedResponse, error)
}

type ticketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTicketServiceClient(cc grpc.ClientConnInterface) TicketServiceClient {
	return &ticketServiceClient{cc}
}

func (c *ticketServiceClient) ListTickets(ctx context.Context, in *ListTicketsRequest, opts ...grpc.CallOption) (*ListTicketsResponse, error) {
	out := new(ListTicketsResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTickets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) GetTicket(ctx context.Context, in *GetTicketRequest, opts ...grpc.CallOption) (*GetTicketResponse, error) {
	out := new(GetTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_GetTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) CreateTicket(ctx context.Context, in *CreateTicketRequest, opts ...grpc.CallOption) (*CreateTicketResponse, error) {
	out := new(CreateTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_CreateTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) UpdateTicket(ctx context.Context, in *UpdateTicketRequest, opts ...grpc.CallOption) (*UpdateTicketResponse, error) {
	out := new(UpdateTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_UpdateTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) DeleteTicket(ctx context.Context, in *DeleteTicketRequest, opts ...grpc.CallOption) (*DeleteTicketResponse, error) {
	out := new(DeleteTicketResponse)
	err := c.cc.Invoke(ctx, TicketService_DeleteTicket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) AddTicketTags(ctx context.Context, in *AddTicketTagsRequest, opts ...grpc.CallOption) (*AddTicketTagsResponse, error) {
	out := new(AddTicketTagsResponse)
	err := c.cc.Invoke(ctx, TicketService_AddTicketTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ListTicketTags(ctx context.Context, in *ListTicketTagsRequest, opts ...grpc.CallOption) (*ListTicketTagsResponse, error) {
	out := new(ListTicketTagsResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTicketTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) DeleteTicketTags(ctx context.Context, in *DeleteTicketTagsRequest, opts ...grpc.CallOption) (*DeleteTicketTagsResponse, error) {
	out := new(DeleteTicketTagsResponse)
	err := c.cc.Invoke(ctx, TicketService_DeleteTicketTags_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, TicketService_Verify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) ListTicketVerifications(ctx context.Context, in *ListTicketVerificationsRequest, opts ...grpc.CallOption) (*ListTicketVerificationsResponse, error) {
	out := new(ListTicketVerificationsResponse)
	err := c.cc.Invoke(ctx, TicketService_ListTicketVerifications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ticketServiceClient) IsApproved(ctx context.Context, in *IsApprovedRequest, opts ...grpc.CallOption) (*IsApprovedResponse, error) {
	out := new(IsApprovedResponse)
	err := c.cc.Invoke(ctx, TicketService_IsApproved_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicketServiceServer is the server API for TicketService service.
// All implementations must embed UnimplementedTicketServiceServer
// for forward compatibility
type TicketServiceServer interface {
	// Lists tickets
	ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error)
	// Gets a ticket
	GetTicket(context.Context, *GetTicketRequest) (*GetTicketResponse, error)
	// Create a ticket
	CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketResponse, error)
	// Updates a ticket
	UpdateTicket(context.Context, *UpdateTicketRequest) (*UpdateTicketResponse, error)
	// Deletes a ticket
	DeleteTicket(context.Context, *DeleteTicketRequest) (*DeleteTicketResponse, error)
	// Add tags
	AddTicketTags(context.Context, *AddTicketTagsRequest) (*AddTicketTagsResponse, error)
	// List tags
	ListTicketTags(context.Context, *ListTicketTagsRequest) (*ListTicketTagsResponse, error)
	// Remove tags
	DeleteTicketTags(context.Context, *DeleteTicketTagsRequest) (*DeleteTicketTagsResponse, error)
	// Verify a ticket
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
	// List ticket verifications
	ListTicketVerifications(context.Context, *ListTicketVerificationsRequest) (*ListTicketVerificationsResponse, error)
	// check whether a ticket is approved
	IsApproved(context.Context, *IsApprovedRequest) (*IsApprovedResponse, error)
	mustEmbedUnimplementedTicketServiceServer()
}

// UnimplementedTicketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTicketServiceServer struct {
}

func (UnimplementedTicketServiceServer) ListTickets(context.Context, *ListTicketsRequest) (*ListTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTickets not implemented")
}
func (UnimplementedTicketServiceServer) GetTicket(context.Context, *GetTicketRequest) (*GetTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicket not implemented")
}
func (UnimplementedTicketServiceServer) CreateTicket(context.Context, *CreateTicketRequest) (*CreateTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTicket not implemented")
}
func (UnimplementedTicketServiceServer) UpdateTicket(context.Context, *UpdateTicketRequest) (*UpdateTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTicket not implemented")
}
func (UnimplementedTicketServiceServer) DeleteTicket(context.Context, *DeleteTicketRequest) (*DeleteTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicket not implemented")
}
func (UnimplementedTicketServiceServer) AddTicketTags(context.Context, *AddTicketTagsRequest) (*AddTicketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTicketTags not implemented")
}
func (UnimplementedTicketServiceServer) ListTicketTags(context.Context, *ListTicketTagsRequest) (*ListTicketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTicketTags not implemented")
}
func (UnimplementedTicketServiceServer) DeleteTicketTags(context.Context, *DeleteTicketTagsRequest) (*DeleteTicketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTicketTags not implemented")
}
func (UnimplementedTicketServiceServer) Verify(context.Context, *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}
func (UnimplementedTicketServiceServer) ListTicketVerifications(context.Context, *ListTicketVerificationsRequest) (*ListTicketVerificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTicketVerifications not implemented")
}
func (UnimplementedTicketServiceServer) IsApproved(context.Context, *IsApprovedRequest) (*IsApprovedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsApproved not implemented")
}
func (UnimplementedTicketServiceServer) mustEmbedUnimplementedTicketServiceServer() {}

// UnsafeTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicketServiceServer will
// result in compilation errors.
type UnsafeTicketServiceServer interface {
	mustEmbedUnimplementedTicketServiceServer()
}

func RegisterTicketServiceServer(s grpc.ServiceRegistrar, srv TicketServiceServer) {
	s.RegisterService(&TicketService_ServiceDesc, srv)
}

func _TicketService_ListTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTickets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTickets(ctx, req.(*ListTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_GetTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).GetTicket(ctx, req.(*GetTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_CreateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).CreateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_CreateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).CreateTicket(ctx, req.(*CreateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_UpdateTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).UpdateTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_UpdateTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).UpdateTicket(ctx, req.(*UpdateTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_DeleteTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).DeleteTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_DeleteTicket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).DeleteTicket(ctx, req.(*DeleteTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_AddTicketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTicketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).AddTicketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_AddTicketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).AddTicketTags(ctx, req.(*AddTicketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ListTicketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTicketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTicketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTicketTags(ctx, req.(*ListTicketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_DeleteTicketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTicketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).DeleteTicketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_DeleteTicketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).DeleteTicketTags(ctx, req.(*DeleteTicketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_Verify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_ListTicketVerifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketVerificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).ListTicketVerifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_ListTicketVerifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).ListTicketVerifications(ctx, req.(*ListTicketVerificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TicketService_IsApproved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsApprovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicketServiceServer).IsApproved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TicketService_IsApproved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicketServiceServer).IsApproved(ctx, req.(*IsApprovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TicketService_ServiceDesc is the grpc.ServiceDesc for TicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tap.verify.v1.TicketService",
	HandlerType: (*TicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTickets",
			Handler:    _TicketService_ListTickets_Handler,
		},
		{
			MethodName: "GetTicket",
			Handler:    _TicketService_GetTicket_Handler,
		},
		{
			MethodName: "CreateTicket",
			Handler:    _TicketService_CreateTicket_Handler,
		},
		{
			MethodName: "UpdateTicket",
			Handler:    _TicketService_UpdateTicket_Handler,
		},
		{
			MethodName: "DeleteTicket",
			Handler:    _TicketService_DeleteTicket_Handler,
		},
		{
			MethodName: "AddTicketTags",
			Handler:    _TicketService_AddTicketTags_Handler,
		},
		{
			MethodName: "ListTicketTags",
			Handler:    _TicketService_ListTicketTags_Handler,
		},
		{
			MethodName: "DeleteTicketTags",
			Handler:    _TicketService_DeleteTicketTags_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _TicketService_Verify_Handler,
		},
		{
			MethodName: "ListTicketVerifications",
			Handler:    _TicketService_ListTicketVerifications_Handler,
		},
		{
			MethodName: "IsApproved",
			Handler:    _TicketService_IsApproved_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tap/verify/v1/tickets.proto",
}
